version: '2'
services:
    jz-app:
        image: jz
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jz-mysql:3306/jz?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jz-elasticsearch:9300
        ports:
            - 8080:8080
    jz-mysql:
        extends:
            file: mysql.yml
            service: jz-mysql
    jz-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jz-elasticsearch
